sudo: false
cache: bundler
bundler_args: --without development

before_install:
  - gem install bundler -v 1.16.0.pre.3
  - gem install rake

rvm:
  - 2.3.5
  - 2.4.2

script: bundle exec rake

branches:
  only:
    - master

services:
  - mongodb
